MAJOR = [
    {
        "num": 0, "name_ru": "Шут", "name_en": "The Fool",
        "kw_ru": ["начало", "спонтанность", "путь"], "kw_en": ["beginnings", "spontaneity", "leap of faith"],
        "ru_upr": "Новое начало и доверие жизни: шаг в неизвестность, который открывает путь.",
        "ru_rev": "Сомнения и страх перемен; поспешность или, наоборот, нерешительность.",
        "en_upr": "A new beginning and trust in life: a leap into the unknown that opens a path.",
        "en_rev": "Doubt and fear of change; rushing or, on the contrary, hesitation.",
    },
    {
        "num": 1, "name_ru": "Маг", "name_en": "The Magician",
        "kw_ru": ["воля", "мастерство", "ресурсы"], "kw_en": ["willpower", "skill", "resources"],
        "ru_upr": "Все ресурсы уже у тебя в руках: воля, мастерство и ясная цель.",
        "ru_rev": "Распылённость, манипуляции или нереализованный потенциал.",
        "en_upr": "Every resource is already in your hands: will, skill and a clear aim.",
        "en_rev": "Scattered energy, manipulation or untapped potential.",
    },
    {
        "num": 2, "name_ru": "Верховная Жрица", "name_en": "The High Priestess",
        "kw_ru": ["интуиция", "тайна", "внутренний голос"], "kw_en": ["intuition", "mystery", "inner voice"],
        "ru_upr": "Ответы внутри: доверься интуиции и не спеши с выводами.",
        "ru_rev": "Интуиция заглушена шумом; что-то скрыто или недоговорено.",
        "en_upr": "The answers are within: trust your intuition and don't rush to conclusions.",
        "en_rev": "Intuition is drowned by noise; something is hidden or unsaid.",
    },
    {
        "num": 3, "name_ru": "Императрица", "name_en": "The Empress",
        "kw_ru": ["изобилие", "творчество", "забота"], "kw_en": ["abundance", "creativity", "nurturing"],
        "ru_upr": "Изобилие и рост: время творчества, заботы и плодов.",
        "ru_rev": "Застой в делах или чувствах; чрезмерная зависимость от других.",
        "en_upr": "Abundance and growth: a time for creativity, care and fruit.",
        "en_rev": "Stagnation in affairs or feelings; over-dependence on others.",
    },
    {
        "num": 4, "name_ru": "Император", "name_en": "The Emperor",
        "kw_ru": ["порядок", "власть", "структура"], "kw_en": ["order", "authority", "structure"],
        "ru_upr": "Порядок и структура: укрепи фундамент и прими ответственность.",
        "ru_rev": "Жёсткость и чрезмерный контроль там, где нужна гибкость.",
        "en_upr": "Order and structure: strengthen the foundation and take responsibility.",
        "en_rev": "Rigidity and over-control where flexibility is needed.",
    },
    {
        "num": 5, "name_ru": "Иерофант", "name_en": "The Hierophant",
        "kw_ru": ["традиция", "учение", "наставник"], "kw_en": ["tradition", "learning", "mentor"],
        "ru_upr": "Учение и традиция: найди наставника или следуй проверенному пути.",
        "ru_rev": "Устаревшие правила; пора пересмотреть убеждения.",
        "en_upr": "Learning and tradition: find a mentor or follow a proven path.",
        "en_rev": "Outdated rules; time to revise your beliefs.",
    },
    {
        "num": 6, "name_ru": "Влюблённые", "name_en": "The Lovers",
        "kw_ru": ["любовь", "выбор", "союз"], "kw_en": ["love", "choice", "union"],
        "ru_upr": "Выбор сердцем и союз: важная связь или решение по любви.",
        "ru_rev": "Внутренний конфликт, разлад, сомнение в выборе.",
        "en_upr": "A choice from the heart: an important bond or a decision of love.",
        "en_rev": "Inner conflict, disharmony, doubt about a choice.",
    },
    {
        "num": 7, "name_ru": "Колесница", "name_en": "The Chariot",
        "kw_ru": ["победа", "воля", "движение"], "kw_en": ["victory", "willpower", "momentum"],
        "ru_upr": "Победа через волю: собери поводья и двигайся к цели.",
        "ru_rev": "Потеря направления; дело буксует без ясного курса.",
        "en_upr": "Victory through will: take the reins and move toward the goal.",
        "en_rev": "Loss of direction; things stall without a clear course.",
    },
    {
        "num": 8, "name_ru": "Сила", "name_en": "Strength",
        "kw_ru": ["сила", "терпение", "смелость"], "kw_en": ["strength", "patience", "courage"],
        "ru_upr": "Мягкая сила: терпение и внутренний стержень побеждают.",
        "ru_rev": "Неуверенность и страх; эмоции выходят из-под контроля.",
        "en_upr": "Gentle strength: patience and inner core prevail.",
        "en_rev": "Self-doubt and fear; emotions slip out of control.",
    },
    {
        "num": 9, "name_ru": "Отшельник", "name_en": "The Hermit",
        "kw_ru": ["уединение", "поиск", "мудрость"], "kw_en": ["solitude", "search", "wisdom"],
        "ru_upr": "Время тишины: уединение принесёт ответ и мудрость.",
        "ru_rev": "Изоляция затянулась; пора вернуться к людям.",
        "en_upr": "A time of quiet: solitude will bring the answer.",
        "en_rev": "Isolation has gone too far; time to return to people.",
    },
    {
        "num": 10, "name_ru": "Колесо Фортуны", "name_en": "Wheel of Fortune",
        "kw_ru": ["судьба", "перемены", "цикл"], "kw_en": ["destiny", "change", "cycle"],
        "ru_upr": "Колесо поворачивается: перемены к лучшему, удачный цикл.",
        "ru_rev": "Полоса задержек; не сопротивляйся переменам.",
        "en_upr": "The wheel turns: change for the better, a lucky cycle.",
        "en_rev": "A stretch of delays; don't resist change.",
    },
    {
        "num": 11, "name_ru": "Справедливость", "name_en": "Justice",
        "kw_ru": ["справедливость", "правда", "баланс"], "kw_en": ["justice", "truth", "balance"],
        "ru_upr": "Справедливое решение: честность и баланс восторжествуют.",
        "ru_rev": "Нечестность или уклонение от ответственности; решение необъективно.",
        "en_upr": "A fair decision: honesty and balance prevail.",
        "en_rev": "Dishonesty or avoidance; a biased decision.",
    },
    {
        "num": 12, "name_ru": "Повешенный", "name_en": "The Hanged Man",
        "kw_ru": ["пауза", "новый взгляд", "жертва"], "kw_en": ["pause", "new perspective", "surrender"],
        "ru_upr": "Пауза и новый угол зрения: отпусти, чтобы выиграть.",
        "ru_rev": "Бессмысленная жертва; зависание без движения.",
        "en_upr": "A pause and a new angle: let go in order to gain.",
        "en_rev": "A pointless sacrifice; stuck with no movement.",
    },
    {
        "num": 13, "name_ru": "Смерть", "name_en": "Death",
        "kw_ru": ["трансформация", "завершение", "обновление"], "kw_en": ["transformation", "endings", "renewal"],
        "ru_upr": "Трансформация: старое завершается, чтобы дать место новому.",
        "ru_rev": "Страх отпустить прошлое; перемены откладываются.",
        "en_upr": "Transformation: the old ends to make way for the new.",
        "en_rev": "Fear of letting go; change is postponed.",
    },
    {
        "num": 14, "name_ru": "Умеренность", "name_en": "Temperance",
        "kw_ru": ["баланс", "умеренность", "терпение"], "kw_en": ["balance", "moderation", "patience"],
        "ru_upr": "Баланс и золотая середина: смешивай противоположности умело.",
        "ru_rev": "Крайности и нетерпение; баланс потерян.",
        "en_upr": "Balance and the golden mean: blend opposites skilfully.",
        "en_rev": "Extremes and impatience; balance is lost.",
    },
    {
        "num": 15, "name_ru": "Дьявол", "name_en": "The Devil",
        "kw_ru": ["искушение", "привязанность", "тень"], "kw_en": ["temptation", "attachment", "shadow"],
        "ru_upr": "Искушения и привязанности: заметь, что держит тебя в плену.",
        "ru_rev": "Освобождение: ты начинаешь видеть и разрывать цепи.",
        "en_upr": "Temptations and attachments: notice what keeps you captive.",
        "en_rev": "Liberation: you begin to see and break the chains.",
    },
    {
        "num": 16, "name_ru": "Башня", "name_en": "The Tower",
        "kw_ru": ["перелом", "откровение", "освобождение"], "kw_en": ["upheaval", "revelation", "release"],
        "ru_upr": "Внезапная перестройка: рушится ложное, освобождая место правде.",
        "ru_rev": "Кризис откладывается; сопротивление неизбежной перестройке.",
        "en_upr": "A sudden overhaul: the false collapses to make room for truth.",
        "en_rev": "A delayed crisis; resisting an inevitable overhaul.",
    },
    {
        "num": 17, "name_ru": "Звезда", "name_en": "The Star",
        "kw_ru": ["надежда", "вдохновение", "исцеление"], "kw_en": ["hope", "inspiration", "healing"],
        "ru_upr": "Надежда и исцеление: путеводная звезда уже взошла.",
        "ru_rev": "Вера слабеет; вдохновение вернётся — не спеши сдаваться.",
        "en_upr": "Hope and healing: the guiding star has risen.",
        "en_rev": "Faith is fading; inspiration will return — don't give up.",
    },
    {
        "num": 18, "name_ru": "Луна", "name_en": "The Moon",
        "kw_ru": ["иллюзии", "тревоги", "подсознание"], "kw_en": ["illusions", "anxiety", "subconscious"],
        "ru_upr": "Туман иллюзий и тревог: не принимай решений вслепую.",
        "ru_rev": "Туман рассеивается; страхи теряют силу.",
        "en_upr": "A fog of illusions and anxieties: don't decide in the dark.",
        "en_rev": "The fog clears; fears lose their grip.",
    },
    {
        "num": 19, "name_ru": "Солнце", "name_en": "The Sun",
        "kw_ru": ["радость", "успех", "ясность"], "kw_en": ["joy", "success", "clarity"],
        "ru_upr": "Ясность, радость и успех: время сиять.",
        "ru_rev": "Успех чуть откладывается; верни себе уверенность.",
        "en_upr": "Clarity, joy and success: time to shine.",
        "en_rev": "Success is slightly delayed; reclaim your confidence.",
    },
    {
        "num": 20, "name_ru": "Суд", "name_en": "Judgement",
        "kw_ru": ["пробуждение", "обновление", "призвание"], "kw_en": ["awakening", "renewal", "calling"],
        "ru_upr": "Пробуждение и обновление: важный вывод меняет путь.",
        "ru_rev": "Самоосуждение; страх услышать свой зов.",
        "en_upr": "Awakening and renewal: an important verdict changes the path.",
        "en_rev": "Self-judgement; fear of hearing your calling.",
    },
    {
        "num": 21, "name_ru": "Мир", "name_en": "The World",
        "kw_ru": ["завершение", "целостность", "гармония"], "kw_en": ["completion", "wholeness", "harmony"],
        "ru_upr": "Завершение и целостность: цикл красиво завершился.",
        "ru_rev": "Шаг до финиша; что-то удерживает от завершения.",
        "en_upr": "Completion and wholeness: a cycle closes beautifully.",
        "en_rev": "One step from the finish; something holds you back.",
    },
]
