MAJOR = [
    {
        "num": 0, "name_ru": "Шут", "name_en": "The Fool",
        "kw_ru": ["начало", "спонтанность", "путь"], "kw_en": ["beginnings", "spontaneity", "leap of faith"],
        "ru_upr": "Новое начало и доверие жизни: шаг в неизвестность, который открывает путь.",
        "ru_rev": "Сомнения и страх перемен; поспешность или, наоборот, нерешительность.",
        "en_upr": "A new beginning and trust in life: a leap into the unknown that opens a path.",
        "en_rev": "Doubt and fear of change; rushing or, on the contrary, hesitation.",
        "ru_upr_light": "Свобода от прошлого даёт любопытство, лёгкость и смелость начать с нуля.",
        "ru_upr_shadow": "Азарт нового может заслонить последствия, детали и реальные ограничения.",
        "ru_upr_advice": "Сделай первый шаг, но заранее проверь один главный риск и путь отступления.",
        "ru_rev_light": "Осторожность даёт время собрать опору и подготовиться к шагу в неизвестность.",
        "ru_rev_shadow": "Страх ошибки удерживает на старте или толкает в резкий, непродуманный рывок.",
        "ru_rev_advice": "Назови конкретный страх и подготовь одно действие, которое уменьшит его силу.",
        "en_upr_light": "Freshness, curiosity and freedom from old baggage make a brave start possible.",
        "en_upr_shadow": "Excitement can eclipse consequences, practical limits and basic preparation.",
        "en_upr_advice": "Take the first step, but check the main risk and your fallback plan beforehand.",
        "en_rev_light": "Caution can buy useful time to build support before entering unfamiliar ground.",
        "en_rev_shadow": "Fear of getting it wrong may freeze you or provoke a reckless leap just to escape doubt.",
        "en_rev_advice": "Name the specific fear, then prepare one practical move that reduces its power.",
    },
    {
        "num": 1, "name_ru": "Маг", "name_en": "The Magician",
        "kw_ru": ["воля", "мастерство", "ресурсы"], "kw_en": ["willpower", "skill", "resources"],
        "ru_upr": "Все ресурсы уже у тебя в руках: воля, мастерство и ясная цель.",
        "ru_rev": "Распылённость, манипуляции или нереализованный потенциал.",
        "en_upr": "Every resource is already in your hands: will, skill and a clear aim.",
        "en_rev": "Scattered energy, manipulation or untapped potential.",
        "ru_upr_light": "Собранная воля превращает знания, навыки и доступные ресурсы в результат.",
        "ru_upr_shadow": "Уверенность легко скатывается в давление, показное мастерство или манипуляцию.",
        "ru_upr_advice": "Выбери одну цель, один главный инструмент и доведи конкретное действие до конца.",
        "ru_rev_light": "Рассеянный потенциал можно вернуть в фокус, если убрать лишние каналы внимания.",
        "ru_rev_shadow": "Самосомнение, хитрость или распыление сил мешают способности стать действием.",
        "ru_rev_advice": "Закрой один отвлекающий канал и примени сильнейший навык к одной понятной задаче.",
        "en_upr_light": "Focused will turns skill, knowledge and available resources into tangible action.",
        "en_upr_shadow": "Confidence can slide into control, showmanship or using skill to manipulate others.",
        "en_upr_advice": "Choose one goal and one key tool, then complete a concrete action before expanding.",
        "en_rev_light": "Scattered ability can become effective again once attention is deliberately narrowed.",
        "en_rev_shadow": "Self-doubt, misdirection or divided effort keeps genuine ability from becoming effective.",
        "en_rev_advice": "Remove one distraction and apply your strongest skill to one clearly defined task.",
    },
    {
        "num": 2, "name_ru": "Верховная Жрица", "name_en": "The High Priestess",
        "kw_ru": ["интуиция", "тайна", "внутренний голос"], "kw_en": ["intuition", "mystery", "inner voice"],
        "ru_upr": "Ответы внутри: доверься интуиции и не спеши с выводами.",
        "ru_rev": "Интуиция заглушена шумом; что-то скрыто или недоговорено.",
        "en_upr": "The answers are within: trust your intuition and don't rush to conclusions.",
        "en_rev": "Intuition is drowned by noise; something is hidden or unsaid.",
        "ru_upr_light": "Тишина усиливает наблюдательность и помогает замечать скрытые связи без спешки.",
        "ru_upr_shadow": "Закрытость может превратить внутреннее знание в пассивность, тайны и недоверие.",
        "ru_upr_advice": "Убери внешний шум на десять минут, запиши первый тихий вывод и сверь его с фактами.",
        "ru_rev_light": "Скрытое становится заметнее, если восстановить контакт с собственными ощущениями.",
        "ru_rev_shadow": "Тревожный шум легко принять за интуицию, а недосказанность — за доказательство.",
        "ru_rev_advice": "Раздели на бумаге факты, догадки и страхи; решение строй только на первых двух.",
        "en_upr_light": "Stillness sharpens perception and helps subtle patterns emerge without forcing them.",
        "en_upr_shadow": "Privacy can harden into passivity, secrecy or distrust of anything that feels unclear.",
        "en_upr_advice": "Take ten quiet minutes, note the first calm insight, then test it against known facts.",
        "en_rev_light": "What was obscured can become readable when you reconnect with your own inner signals.",
        "en_rev_shadow": "Anxiety may masquerade as intuition, while missing information starts to look certain.",
        "en_rev_advice": "Write three columns: facts, assumptions and fears; base the next move on the first two.",
    },
    {
        "num": 3, "name_ru": "Императрица", "name_en": "The Empress",
        "kw_ru": ["изобилие", "творчество", "забота"], "kw_en": ["abundance", "creativity", "nurturing"],
        "ru_upr": "Изобилие и рост: время творчества, заботы и плодов.",
        "ru_rev": "Застой в делах или чувствах; чрезмерная зависимость от других.",
        "en_upr": "Abundance and growth: a time for creativity, care and fruit.",
        "en_rev": "Stagnation in affairs or feelings; over-dependence on others.",
        "ru_upr_light": "Творческая и телесная щедрость помогает растить то, что требует времени и заботы.",
        "ru_upr_shadow": "Забота без границ превращается в опеку, излишества или жизнь чужими потребностями.",
        "ru_upr_advice": "Создай что-то осязаемое сегодня и отдельно проверь, хватает ли тебе сна и отдыха.",
        "ru_rev_light": "Возврат внимания к себе способен восстановить иссякший запас тепла и творчества.",
        "ru_rev_shadow": "Истощение, зависимость от одобрения или чрезмерная опека блокируют естественный рост.",
        "ru_rev_advice": "Откажись от одной истощающей обязанности и восстанови одну базовую потребность тела.",
        "en_upr_light": "Creative care and steady nourishment help something worthwhile grow at a natural pace.",
        "en_upr_shadow": "Nurturing without boundaries can become overgiving, indulgence or living for others.",
        "en_upr_advice": "Make something tangible today, then check whether your body is getting enough rest.",
        "en_rev_light": "Turning care inward can restore creative energy that has been spent too freely.",
        "en_rev_shadow": "Depletion, approval-seeking or smothering care can interrupt healthy growth.",
        "en_rev_advice": "Drop one draining obligation and deliberately restore one basic physical need.",
    },
    {
        "num": 4, "name_ru": "Император", "name_en": "The Emperor",
        "kw_ru": ["порядок", "власть", "структура"], "kw_en": ["order", "authority", "structure"],
        "ru_upr": "Порядок и структура: укрепи фундамент и прими ответственность.",
        "ru_rev": "Жёсткость и чрезмерный контроль там, где нужна гибкость.",
        "en_upr": "Order and structure: strengthen the foundation and take responsibility.",
        "en_rev": "Rigidity and over-control where flexibility is needed.",
        "ru_upr_light": "Ясные границы и ответственность создают порядок, на который можно опереться надолго.",
        "ru_upr_shadow": "Структура становится жёсткой, когда контроль важнее людей, контекста и здравого смысла.",
        "ru_upr_advice": "Зафиксируй одно правило, срок и зону ответственности — и не меняй их без веской причины.",
        "ru_rev_light": "Ослабление контроля открывает место гибкости, переговорам и более живой структуре.",
        "ru_rev_shadow": "Либо власть душит процесс, либо отказ от ответственности оставляет его без опоры.",
        "ru_rev_advice": "Найди зону чрезмерного контроля и зону без ясной ответственности; выровняй границы.",
        "en_upr_light": "Clear boundaries and ownership create a structure people can reliably work within.",
        "en_upr_shadow": "Order becomes brittle when control matters more than context, people or good judgement.",
        "en_upr_advice": "Define one rule, one deadline and who is responsible; change them only for a solid reason.",
        "en_rev_light": "Loosening rigid control can make room for negotiation, flexibility and better design.",
        "en_rev_shadow": "Either authority is choking the process or nobody is willing to hold responsibility.",
        "en_rev_advice": "Find one overcontrolled area and one area with unclear responsibility, then rebalance both.",
    },
    {
        "num": 5, "name_ru": "Иерофант", "name_en": "The Hierophant",
        "kw_ru": ["традиция", "учение", "наставник"], "kw_en": ["tradition", "learning", "mentor"],
        "ru_upr": "Учение и традиция: найди наставника или следуй проверенному пути.",
        "ru_rev": "Устаревшие правила; пора пересмотреть убеждения.",
        "en_upr": "Learning and tradition: find a mentor or follow a proven path.",
        "en_rev": "Outdated rules; time to revise your beliefs.",
        "ru_upr_light": "Проверенная традиция и хороший наставник дают язык, рамку и опыт предыдущих поколений.",
        "ru_upr_shadow": "Правило теряет смысл, когда его соблюдают из страха, привычки или ради одобрения группы.",
        "ru_upr_advice": "Спроси опытного человека, зачем существует правило, и сопоставь ответ со своими ценностями.",
        "ru_rev_light": "Сомнение в авторитете помогает отделить живое знание от пустой формы и привычки.",
        "ru_rev_shadow": "Бунт ради самого бунта оставляет без опоры так же легко, как слепое подчинение.",
        "ru_rev_advice": "Выбери одно унаследованное правило и проверь на практике, какую пользу оно даёт сейчас.",
        "en_upr_light": "A sound tradition or mentor offers language, structure and experience you need not reinvent.",
        "en_upr_shadow": "A useful rule becomes dogma when obedience matters more than purpose or conscience.",
        "en_upr_advice": "Ask an experienced person why the rule exists, then compare the answer with your values.",
        "en_rev_light": "Questioning authority can separate living wisdom from habit, status and empty form.",
        "en_rev_shadow": "Rebellion for its own sake can leave you as ungrounded as unquestioning conformity.",
        "en_rev_advice": "Choose one inherited rule and test what practical value it still provides today.",
    },
    {
        "num": 6, "name_ru": "Влюблённые", "name_en": "The Lovers",
        "kw_ru": ["любовь", "выбор", "союз"], "kw_en": ["love", "choice", "union"],
        "ru_upr": "Выбор сердцем и союз: важная связь или решение по любви.",
        "ru_rev": "Внутренний конфликт, разлад, сомнение в выборе.",
        "en_upr": "A choice from the heart: an important bond or a decision of love.",
        "en_rev": "Inner conflict, disharmony, doubt about a choice.",
        "ru_upr_light": "Согласованность чувств, ценностей и выбора делает союз честнее, а решение устойчивее.",
        "ru_upr_shadow": "Сильное притяжение может скрыть идеализацию, зависимость или отказ сделать выбор.",
        "ru_upr_advice": "Назови три главные ценности и выбери действие, которое не противоречит ни одной из них.",
        "ru_rev_light": "Разлад ясно показывает, где желания, обещания и реальные ценности перестали совпадать.",
        "ru_rev_shadow": "Внутренний раскол ведёт к двойным сигналам, откладыванию решения и нечестным компромиссам.",
        "ru_rev_advice": "Определи принцип, которым нельзя жертвовать, и обсуди конкретное расхождение.",
        "en_upr_light": "When desire, values and choice align, a bond becomes clearer and a decision more durable.",
        "en_upr_shadow": "Strong attraction can hide idealisation, dependency or reluctance to make a real choice.",
        "en_upr_advice": "Name your three core values and choose an action that does not betray any of them.",
        "en_rev_light": "Disharmony reveals exactly where wishes, promises and lived values no longer match.",
        "en_rev_shadow": "Inner division creates mixed signals, delayed decisions and compromises you cannot own.",
        "en_rev_advice": "Define one non-negotiable value and address the specific mismatch rather than the mood.",
    },
    {
        "num": 7, "name_ru": "Колесница", "name_en": "The Chariot",
        "kw_ru": ["победа", "воля", "движение"], "kw_en": ["victory", "willpower", "momentum"],
        "ru_upr": "Победа через волю: собери поводья и двигайся к цели.",
        "ru_rev": "Потеря направления; дело буксует без ясного курса.",
        "en_upr": "Victory through will: take the reins and move toward the goal.",
        "en_rev": "Loss of direction; things stall without a clear course.",
        "ru_upr_light": "Направленная воля соединяет противоречивые импульсы и превращает усилие в движение к цели.",
        "ru_upr_shadow": "Напор становится опасным, когда скорость, победа и контроль вытесняют проверку курса.",
        "ru_upr_advice": "Выбери маршрут и ближайшую контрольную точку; держи темп, не распыляясь на боковые задачи.",
        "ru_rev_light": "Остановка может уберечь от неверного курса и дать возможность заново собрать управление.",
        "ru_rev_shadow": "Разные желания тянут в стороны; раздражение или пассивность подменяют ясное направление.",
        "ru_rev_advice": "Остановись, выбери одну точку назначения и на сутки убери две конкурирующие задачи.",
        "en_upr_light": "Directed will can harness conflicting impulses and turn effort into steady forward motion.",
        "en_upr_shadow": "Drive becomes dangerous when speed, winning and control replace checking the direction.",
        "en_upr_advice": "Set the route and next checkpoint; keep pace without adding distracting side tasks.",
        "en_rev_light": "A deliberate stop can prevent a wrong turn and give you time to regain the reins.",
        "en_rev_shadow": "Competing drives pull apart, while frustration or passivity replaces clear direction.",
        "en_rev_advice": "Stop, choose one destination and remove two competing tasks from the next twenty-four hours.",
    },
    {
        "num": 8, "name_ru": "Сила", "name_en": "Strength",
        "kw_ru": ["сила", "терпение", "смелость"], "kw_en": ["strength", "patience", "courage"],
        "ru_upr": "Мягкая сила: терпение и внутренний стержень побеждают.",
        "ru_rev": "Неуверенность и страх; эмоции выходят из-под контроля.",
        "en_upr": "Gentle strength: patience and inner core prevail.",
        "en_rev": "Self-doubt and fear; emotions slip out of control.",
        "ru_upr_light": "Спокойная смелость позволяет выдерживать сильные чувства без подавления и без капитуляции.",
        "ru_upr_shadow": "Терпение и самообладание могут маскировать подавленный гнев или привычку всё терпеть.",
        "ru_upr_advice": "Назови сильную эмоцию и выбери твёрдое, но не агрессивное действие в ответ на неё.",
        "ru_rev_light": "Уязвимость точно показывает место, где нужен не нажим, а восстановление внутренней опоры.",
        "ru_rev_shadow": "Самосомнение или непрожитые эмоции перехватывают управление и уменьшают свободу выбора.",
        "ru_rev_advice": "Снизь нагрузку, назови чувство и сделай один небольшой поступок, который требует смелости.",
        "en_upr_light": "Quiet courage lets you hold strong emotion without suppressing it or surrendering to it.",
        "en_upr_shadow": "Composure can conceal buried anger, self-denial or a habit of tolerating too much.",
        "en_upr_advice": "Name the strongest emotion, then choose one firm action that does not become aggression.",
        "en_rev_light": "Vulnerability can pinpoint where pressure will fail and inner support needs rebuilding.",
        "en_rev_shadow": "Self-doubt or unprocessed emotion can take the wheel and shrink your range of choices.",
        "en_rev_advice": "Reduce the pressure, name the feeling and take one small action that still requires courage.",
    },
    {
        "num": 9, "name_ru": "Отшельник", "name_en": "The Hermit",
        "kw_ru": ["уединение", "поиск", "мудрость"], "kw_en": ["solitude", "search", "wisdom"],
        "ru_upr": "Время тишины: уединение принесёт ответ и мудрость.",
        "ru_rev": "Изоляция затянулась; пора вернуться к людям.",
        "en_upr": "A time of quiet: solitude will bring the answer.",
        "en_rev": "Isolation has gone too far; time to return to people.",
        "ru_upr_light": "Добровольное уединение отделяет собственный вывод от чужого шума и спешки окружающих.",
        "ru_upr_shadow": "Поиск глубины превращается в изоляцию, если дистанция становится способом не участвовать.",
        "ru_upr_advice": "Выдели час без входящих сообщений, сформулируй один вывод и затем верни его в реальную жизнь.",
        "ru_rev_light": "Ощущение одиночества может стать точным сигналом, что пора восстановить значимую связь.",
        "ru_rev_shadow": "Изоляция подпитывает зацикленность, а размышления начинают заменять опыт и отношения.",
        "ru_rev_advice": "Свяжись с одним надёжным человеком и заранее задай предел времени для дальнейшего уединения.",
        "en_upr_light": "Chosen solitude separates your own judgement from noise, urgency and other people’s agendas.",
        "en_upr_shadow": "The search for depth becomes avoidance when distance is used to stay outside real life.",
        "en_upr_advice": "Take one hour without incoming messages, form one conclusion, then test it in real life.",
        "en_rev_light": "Loneliness can be useful information that a meaningful connection now needs restoring.",
        "en_rev_shadow": "Isolation feeds rumination until reflection begins replacing experience and relationship.",
        "en_rev_advice": "Contact one trusted person and set a clear time limit on further withdrawal.",
    },
    {
        "num": 10, "name_ru": "Колесо Фортуны", "name_en": "Wheel of Fortune",
        "kw_ru": ["судьба", "перемены", "цикл"], "kw_en": ["destiny", "change", "cycle"],
        "ru_upr": "Колесо поворачивается: перемены к лучшему, удачный цикл.",
        "ru_rev": "Полоса задержек; не сопротивляйся переменам.",
        "en_upr": "The wheel turns: change for the better, a lucky cycle.",
        "en_rev": "A stretch of delays; don't resist change.",
        "ru_upr_light": "Гибкость помогает заметить удачный момент и использовать сдвиг обстоятельств без иллюзии контроля.",
        "ru_upr_shadow": "Надежда на удачу превращает участие в пассивное ожидание, будто личный выбор ничего не решает.",
        "ru_upr_advice": "Отметь, что уже сдвинулось вокруг тебя, и используй один шанс, пока окно остаётся открытым.",
        "ru_rev_light": "Повторяющийся рисунок становится видимым, а значит появляется возможность разорвать петлю.",
        "ru_rev_shadow": "Сопротивление циклу усиливает чувство бессилия и заставляет повторять прежнюю реакцию.",
        "ru_rev_advice": "Найди один повторяющийся сценарий и измени в нём только ту реакцию, которую контролируешь.",
        "en_upr_light": "Adaptability helps you catch favourable timing without pretending you control the whole cycle.",
        "en_upr_shadow": "Trust in luck becomes passivity when you act as though personal choices no longer matter.",
        "en_upr_advice": "Notice what has already shifted and use one available opening while it is still open.",
        "en_rev_light": "A repeating pattern becomes useful once you can see it clearly enough to interrupt it.",
        "en_rev_shadow": "Resistance to the cycle can deepen helplessness and keep the same response repeating.",
        "en_rev_advice": "Identify one recurring loop and change only the part of your response you can control.",
    },
    {
        "num": 11, "name_ru": "Справедливость", "name_en": "Justice",
        "kw_ru": ["справедливость", "правда", "баланс"], "kw_en": ["justice", "truth", "balance"],
        "ru_upr": "Справедливое решение: честность и баланс восторжествуют.",
        "ru_rev": "Нечестность или уклонение от ответственности; решение необъективно.",
        "en_upr": "A fair decision: honesty and balance prevail.",
        "en_rev": "Dishonesty or avoidance; a biased decision.",
        "ru_upr_light": "Ясные факты и готовность отвечать за последствия создают честную основу для решения.",
        "ru_upr_shadow": "Стремление доказать правоту превращает принципиальность в холодность, буквоедство или осуждение.",
        "ru_upr_advice": "Выпиши факты, обязательства и последствия; примени к себе то же правило, что и к другим.",
        "ru_rev_light": "Замеченная предвзятость уже даёт возможность исправить перекос до окончательного решения.",
        "ru_rev_shadow": "Отрицание ответственности, двойные стандарты или удобная версия фактов искажают оценку.",
        "ru_rev_advice": "Отдели факты от оправданий и исправь один дисбаланс, который действительно зависит от тебя.",
        "en_upr_light": "Clear facts and ownership of consequences provide a fair foundation for making a decision.",
        "en_upr_shadow": "Wanting to be right can turn principle into coldness, legalism or moral superiority.",
        "en_upr_advice": "List facts, duties and consequences, then apply the same standard to yourself and others.",
        "en_rev_light": "Recognising bias creates a real chance to correct the imbalance before a decision hardens.",
        "en_rev_shadow": "Denial, double standards or a convenient version of events can distort the judgement.",
        "en_rev_advice": "Separate facts from excuses and correct one imbalance that is genuinely within your control.",
    },
    {
        "num": 12, "name_ru": "Повешенный", "name_en": "The Hanged Man",
        "kw_ru": ["пауза", "новый взгляд", "жертва"], "kw_en": ["pause", "new perspective", "surrender"],
        "ru_upr": "Пауза и новый угол зрения: отпусти, чтобы выиграть.",
        "ru_rev": "Бессмысленная жертва; зависание без движения.",
        "en_upr": "A pause and a new angle: let go in order to gain.",
        "en_rev": "A pointless sacrifice; stuck with no movement.",
        "ru_upr_light": "Добровольная пауза освобождает взгляд от привычной позиции и показывает другую систему координат.",
        "ru_upr_shadow": "Отказ действовать становится ловушкой, если жертвенность придаёт зависанию особый смысл.",
        "ru_upr_advice": "Временно отложи одно убеждение и опиши ситуацию с противоположной точки зрения.",
        "ru_rev_light": "Нетерпение может означать, что новый взгляд уже найден и пауза выполнила свою задачу.",
        "ru_rev_shadow": "Сопротивление отпусканию продлевает зависание, а ожидание уже ничего не добавляет.",
        "ru_rev_advice": "Спроси, что именно даёт тебе дальнейшее ожидание, и назначь конкретный срок для шага.",
        "en_upr_light": "A chosen pause releases you from the usual angle and makes a different perspective possible.",
        "en_upr_shadow": "Suspension becomes a trap when sacrifice itself starts to provide identity or moral value.",
        "en_upr_advice": "Set aside one assumption for now and describe the situation from the opposite viewpoint.",
        "en_rev_light": "Impatience may signal that the new perspective has arrived and the pause has done its work.",
        "en_rev_shadow": "Resistance to letting go prolongs suspension even when waiting no longer adds insight.",
        "en_rev_advice": "Ask what further waiting actually gives you, then set a specific deadline for movement.",
    },
    {
        "num": 13, "name_ru": "Смерть", "name_en": "Death",
        "kw_ru": ["трансформация", "завершение", "обновление"], "kw_en": ["transformation", "endings", "renewal"],
        "ru_upr": "Трансформация: старое завершается, чтобы дать место новому.",
        "ru_rev": "Страх отпустить прошлое; перемены откладываются.",
        "en_upr": "Transformation: the old ends to make way for the new.",
        "en_rev": "Fear of letting go; change is postponed.",
        "ru_upr_light": "Честное завершение освобождает энергию, занятую формой, которая уже выполнила свою работу.",
        "ru_upr_shadow": "Резкость отсечения может разрушить полезное вместе с отжившим или превратить конец в драму.",
        "ru_upr_advice": "Закрой одно завершённое дело физически: убери остатки, документы или выполни последний шаг.",
        "ru_rev_light": "Медленное отпускание даёт время прожить окончание и сохранить то, что действительно ценно.",
        "ru_rev_shadow": "Привязанность к исчерпанной форме заставляет снова оживлять то, что уже не работает.",
        "ru_rev_advice": "Назови, что уже закончилось, и сделай один небольшой шаг, который нельзя тихо отменить завтра.",
        "en_upr_light": "A clean ending releases energy that has been tied to a form whose work is already complete.",
        "en_upr_shadow": "Cutting too sharply can destroy what still matters or turn a necessary ending into drama.",
        "en_upr_advice": "Close one finished matter physically: clear the remnants, paperwork or final obligation.",
        "en_rev_light": "A slower release can give grief and adjustment enough time without denying the ending.",
        "en_rev_shadow": "Attachment to an expired form keeps reviving something that can no longer function well.",
        "en_rev_advice": "Name what has already ended, then take one small step that cannot be quietly undone tomorrow.",
    },
    {
        "num": 14, "name_ru": "Умеренность", "name_en": "Temperance",
        "kw_ru": ["баланс", "умеренность", "терпение"], "kw_en": ["balance", "moderation", "patience"],
        "ru_upr": "Баланс и золотая середина: смешивай противоположности умело.",
        "ru_rev": "Крайности и нетерпение; баланс потерян.",
        "en_upr": "Balance and the golden mean: blend opposites skilfully.",
        "en_rev": "Extremes and impatience; balance is lost.",
        "ru_upr_light": "Точная мера соединяет разные силы так, что каждая сохраняет ценность и поддерживает другую.",
        "ru_upr_shadow": "Стремление к ровности может разбавить сильное желание или отложить необходимое решение.",
        "ru_upr_advice": "Между двумя крайностями выбери умеренную меру и проверь, что удаётся поддерживать.",
        "ru_rev_light": "Дисбаланс полезен как индикатор: он показывает, где слишком много, мало или слишком быстро.",
        "ru_rev_shadow": "Качание между крайностями и нетерпение мешают частям процесса соединиться в устойчивый ритм.",
        "ru_rev_advice": "На неделю сократи один избыток и добавь один недостающий элемент, затем оцени результат.",
        "en_upr_light": "Good proportion lets different forces retain their value while supporting one another.",
        "en_upr_shadow": "The pursuit of balance can dilute a strong desire or postpone a decision that needs clarity.",
        "en_upr_advice": "Between two extremes, try a measured middle course and notice what becomes sustainable.",
        "en_rev_light": "Imbalance is useful information: it reveals what is excessive, missing or moving too fast.",
        "en_rev_shadow": "Swinging between extremes prevents the separate parts from settling into a workable rhythm.",
        "en_rev_advice": "For one week, reduce one excess and restore one missing element, then review the effect.",
    },
    {
        "num": 15, "name_ru": "Дьявол", "name_en": "The Devil",
        "kw_ru": ["искушение", "привязанность", "тень"], "kw_en": ["temptation", "attachment", "shadow"],
        "ru_upr": "Искушения и привязанности: заметь, что держит тебя в плену.",
        "ru_rev": "Освобождение: ты начинаешь видеть и разрывать цепи.",
        "en_upr": "Temptations and attachments: notice what keeps you captive.",
        "en_rev": "Liberation: you begin to see and break the chains.",
        "ru_upr_light": "Честный взгляд на желание показывает, какую выгоду дают привычка, зависимость или запретная тяга.",
        "ru_upr_shadow": "Удовольствие превращается в цепь, когда стыд, компульсия или власть уменьшают свободу выбора.",
        "ru_upr_advice": "Назови награду, ради которой держится привязка, и убери один триггер или добавь препятствие.",
        "ru_rev_light": "Осознание собственной роли возвращает способность снять цепь, которая казалась внешней.",
        "ru_rev_shadow": "Отрицание риска создаёт почву для возврата старой привязки под новым названием или формой.",
        "ru_rev_advice": "Создай одну границу, которую трудно обойти автоматически, и попроси конкретную поддержку.",
        "en_upr_light": "An honest look at desire reveals what reward a habit, attachment or taboo pull is providing.",
        "en_upr_shadow": "Pleasure becomes a chain when shame, compulsion or power starts reducing freedom of choice.",
        "en_upr_advice": "Name the reward maintaining the attachment, then remove one trigger or make repetition harder.",
        "en_rev_light": "Seeing your own role restores the ability to loosen a chain that once seemed purely external.",
        "en_rev_shadow": "Denial can invite the same attachment back under a cleaner label or a different form.",
        "en_rev_advice": "Create one boundary that is hard to bypass automatically and ask for specific support.",
    },
    {
        "num": 16, "name_ru": "Башня", "name_en": "The Tower",
        "kw_ru": ["перелом", "откровение", "освобождение"], "kw_en": ["upheaval", "revelation", "release"],
        "ru_upr": "Внезапная перестройка: рушится ложное, освобождая место правде.",
        "ru_rev": "Кризис откладывается; сопротивление неизбежной перестройке.",
        "en_upr": "A sudden overhaul: the false collapses to make room for truth.",
        "en_rev": "A delayed crisis; resisting an inevitable overhaul.",
        "ru_upr_light": "Разрушение ложной опоры освобождает правду и место для конструкции, способной выдержать реальность.",
        "ru_upr_shadow": "Шок провоцирует реакцию сжечь всё подряд, хотя часть структуры может оставаться полезной.",
        "ru_upr_advice": "Сначала защити базовые ресурсы, затем отпусти одно убеждение, которое уже опровергнуто фактами.",
        "ru_rev_light": "Ранний сигнал позволяет разобрать слабую конструкцию контролируемо, не дожидаясь обвала.",
        "ru_rev_shadow": "Избегание очевидной трещины накапливает давление и переносит кризис внутрь или на потом.",
        "ru_rev_advice": "Назови самое слабое место конструкции и измени его сейчас, пока способ действия ещё под контролем.",
        "en_upr_light": "The collapse of a false support exposes truth quickly and clears space for stronger structure.",
        "en_upr_shadow": "Shock can trigger a scorched-earth reaction even when part of the structure is still useful.",
        "en_upr_advice": "Secure the essentials first, then let go of one belief the evidence has already disproved.",
        "en_rev_light": "An early warning allows controlled dismantling before the weak structure collapses by itself.",
        "en_rev_shadow": "Avoiding an obvious crack stores pressure and pushes the crisis inward or further down the road.",
        "en_rev_advice": "Name the weakest part of the structure and change it now, while you still control the method.",
    },
    {
        "num": 17, "name_ru": "Звезда", "name_en": "The Star",
        "kw_ru": ["надежда", "вдохновение", "исцеление"], "kw_en": ["hope", "inspiration", "healing"],
        "ru_upr": "Надежда и исцеление: путеводная звезда уже взошла.",
        "ru_rev": "Вера слабеет; вдохновение вернётся — не спеши сдаваться.",
        "en_upr": "Hope and healing: the guiding star has risen.",
        "en_rev": "Faith is fading; inspiration will return — don't give up.",
        "ru_upr_light": "Спокойная надежда возвращает перспективу, открытость и способность восстанавливаться без спешки.",
        "ru_upr_shadow": "Надежда становится пассивной, если красивый образ будущего заменяет участие в настоящем.",
        "ru_upr_advice": "Сделай одно небольшое восстанавливающее действие, которое поддерживает дальнюю цель уже сегодня.",
        "ru_rev_light": "Сомнение помогает проверить, на чём держится надежда, и сделать её более реалистичной.",
        "ru_rev_shadow": "Сравнение и усталость заставляют считать медленный прогресс доказательством провала.",
        "ru_rev_advice": "Убери один источник сравнения и зафиксируй один конкретный признак того, что восстановление идёт.",
        "en_upr_light": "Quiet hope restores perspective, openness and the capacity to recover without forcing the pace.",
        "en_upr_shadow": "Hope becomes passive when a beautiful future image substitutes for participation in the present.",
        "en_upr_advice": "Do one small restorative action today that genuinely supports the longer horizon you want.",
        "en_rev_light": "Doubt can test what your hope is built on and make it more realistic rather than weaker.",
        "en_rev_shadow": "Comparison, fatigue or cynicism can turn slow progress into false evidence of failure.",
        "en_rev_advice": "Remove one source of comparison and record one concrete sign that recovery is still happening.",
    },
    {
        "num": 18, "name_ru": "Луна", "name_en": "The Moon",
        "kw_ru": ["иллюзии", "тревоги", "подсознание"], "kw_en": ["illusions", "anxiety", "subconscious"],
        "ru_upr": "Туман иллюзий и тревог: не принимай решений вслепую.",
        "ru_rev": "Туман рассеивается; страхи теряют силу.",
        "en_upr": "A fog of illusions and anxieties: don't decide in the dark.",
        "en_rev": "The fog clears; fears lose their grip.",
        "ru_upr_light": "Воображение и чувствительность помогают выдерживать неопределённость, не требуя мгновенной ясности.",
        "ru_upr_shadow": "Страх и проекции заполняют пробелы истории, пока предположение не начинает казаться фактом.",
        "ru_upr_advice": "Не принимай необратимое решение сегодня; сначала проверь два факта, которых тебе не хватает.",
        "ru_rev_light": "Скрытый рисунок становится яснее, когда эмоции перестают полностью окрашивать восприятие.",
        "ru_rev_shadow": "Желание любой ценой получить определённость может создать новую иллюзию вместо прежней.",
        "ru_rev_advice": "Возьми один страх и выпиши отдельно: что известно, что предполагается и что ещё можно проверить.",
        "en_upr_light": "Imagination and sensitivity help you tolerate uncertainty without demanding instant clarity.",
        "en_upr_shadow": "Fear and projection fill gaps in the story until an assumption begins to feel like a fact.",
        "en_upr_advice": "Delay any irreversible decision today and verify two missing facts before moving further.",
        "en_rev_light": "A hidden pattern becomes clearer once emotion is no longer colouring the entire picture.",
        "en_rev_shadow": "The need for certainty can manufacture a new illusion just as the old one is beginning to fade.",
        "en_rev_advice": "Take one fear and separate what is known, assumed and still verifiable before acting on it.",
    },
    {
        "num": 19, "name_ru": "Солнце", "name_en": "The Sun",
        "kw_ru": ["радость", "успех", "ясность"], "kw_en": ["joy", "success", "clarity"],
        "ru_upr": "Ясность, радость и успех: время сиять.",
        "ru_rev": "Успех чуть откладывается; верни себе уверенность.",
        "en_upr": "Clarity, joy and success: time to shine.",
        "en_rev": "Success is slightly delayed; reclaim your confidence.",
        "ru_upr_light": "Открытая радость и ясность дают энергию действовать без лишних сомнений и делиться результатом.",
        "ru_upr_shadow": "Уверенность становится слепым пятном, если успех требует постоянного внимания и восхищения.",
        "ru_upr_advice": "Сделай результат видимым, поблагодари тех, кто помог, и отметь конкретно, что сработало.",
        "ru_rev_light": "Даже приглушённая радость остаётся доступной через простые вещи, тело и честное признание успеха.",
        "ru_rev_shadow": "Хорошее обесценивается, если оно кажется недостаточно ярким, быстрым или идеальным.",
        "ru_rev_advice": "Назови три вещи, которые уже работают, и убери одну привычку, заметно снижающую энергию.",
        "en_upr_light": "Open joy and clarity provide energy to act without needless doubt and to share the result.",
        "en_upr_shadow": "Confidence becomes a blind spot when success depends on constant attention or admiration.",
        "en_upr_advice": "Make the result visible, credit the people who helped and name exactly what worked.",
        "en_rev_light": "Even muted joy remains accessible through simple pleasures, rest and honest recognition.",
        "en_rev_shadow": "Something good can feel worthless when it is not bright, fast or perfect enough to satisfy.",
        "en_rev_advice": "Name three things that already work, then remove one habit that noticeably drains your energy.",
    },
    {
        "num": 20, "name_ru": "Суд", "name_en": "Judgement",
        "kw_ru": ["пробуждение", "обновление", "призвание"], "kw_en": ["awakening", "renewal", "calling"],
        "ru_upr": "Пробуждение и обновление: важный вывод меняет путь.",
        "ru_rev": "Самоосуждение; страх услышать свой зов.",
        "en_upr": "Awakening and renewal: an important verdict changes the path.",
        "en_rev": "Self-judgement; fear of hearing your calling.",
        "ru_upr_light": "Честный итог связывает прошлый опыт с новым уровнем ответственности и ясным внутренним зовом.",
        "ru_upr_shadow": "Пробуждение легко перепутать с моральным превосходством или слишком суровым приговором себе.",
        "ru_upr_advice": "Пересмотри один старый эпизод по фактам и выбери действие, которым ответишь на вывод сейчас.",
        "ru_rev_light": "Внутренняя переоценка даёт второй шанс, если урок отделён от бесконечного самонаказания.",
        "ru_rev_shadow": "Стыд и избегание мешают ответить на очевидный зов и удерживают внимание в старом решении.",
        "ru_rev_advice": "Отдели урок от наказания и сделай один поступок, который закрывает старый долг перед собой.",
        "en_upr_light": "An honest reckoning links past experience with greater responsibility and a clearer calling.",
        "en_upr_shadow": "Awakening can be confused with moral superiority or an unnecessarily harsh verdict on yourself.",
        "en_upr_advice": "Review one past episode by the facts, then choose the action that answers its lesson now.",
        "en_rev_light": "Inner review offers a second chance when learning is separated from endless self-punishment.",
        "en_rev_shadow": "Shame and avoidance can mute an obvious calling and keep attention trapped in an old verdict.",
        "en_rev_advice": "Separate the lesson from punishment and take one action that resolves unfinished business.",
    },
    {
        "num": 21, "name_ru": "Мир", "name_en": "The World",
        "kw_ru": ["завершение", "целостность", "гармония"], "kw_en": ["completion", "wholeness", "harmony"],
        "ru_upr": "Завершение и целостность: цикл красиво завершился.",
        "ru_rev": "Шаг до финиша; что-то удерживает от завершения.",
        "en_upr": "Completion and wholeness: a cycle closes beautifully.",
        "en_rev": "One step from the finish; something holds you back.",
        "ru_upr_light": "Завершённость соединяет опыт в целое и даёт право признать мастерство без дальнейших доказательств.",
        "ru_upr_shadow": "Нежелание закончить превращает мастерство в бесконечную полировку и страх поставить точку.",
        "ru_upr_advice": "Отметь завершение, запиши один главный урок и физически освободи место для следующей работы.",
        "ru_rev_light": "Незакрытая деталь становится видимой, поэтому завершение теперь можно сделать точным и честным.",
        "ru_rev_shadow": "Последний шаг откладывается из-за перфекционизма, рассеянности или нежелания отпустить результат.",
        "ru_rev_advice": "Назови единственную недостающую деталь и закончи её до того, как начнёшь новый большой цикл.",
        "en_upr_light": "Completion integrates experience into a whole and lets earned mastery be recognised as enough.",
        "en_upr_shadow": "Reluctance to finish can turn mastery into endless polishing and fear of placing the final mark.",
        "en_upr_advice": "Mark the completion, record one central lesson and physically clear space for the next work.",
        "en_rev_light": "The unfinished detail is now visible, making an accurate and honest completion possible.",
        "en_rev_shadow": "The final step is delayed by perfectionism, distraction or reluctance to release the result.",
        "en_rev_advice": "Name the single missing piece and finish it before beginning another major cycle.",
    },
]
